### ISSUE TITLE
database: Upvote and Downvote 

### ISSUE THREAD

**Issue by EugeneTeu** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15#56]
- store "upvote" counter 
- upvote collection 
   - each upvote has `{ _uid , _questionId }` user upvotes we update this along w the counter
 - repeat the same

**Comment by AaronCQL** [comment]
## General

- New collection `votes` to store all upvotes and downvotes of every question and answer
- The schema for a `votes` document is already defined as `Vote`
- Each `Vote` document will either have an `answerId` key or an `questionId` key, but never both at the same time

## Schema

The `BaseVote` interface in `modes/Vote.ts` should be changed to:

```ts
interface BaseVote extends Util {
  userId: ObjectId;
  type: 1 | -1; // changed from VoteType
}
```

- The `type` key is used to indicate the type of vote, such that `1` is upvote, `-1` is downvote
- Putting `VoteType` means type checking will fail and can be used to create a `Vote` with `type` that is some other number for example
- We can still use `VoteType` in the codebase to avoid using magic numbers

## Implementation

Route to upvote should be `POST /api/questions/:id/upvote` to upvote, and similarly to downvote and for answers. Upvoting a question/answer should do the following:

1. Find if ques/ans exists
2. Increment its `upvotes` or `downvotes` field by 1
3. Create a new `Vote` document linking the user to the ques/ans

Don't think we need to replicate the votes in the `User` document, since we can retrieve all votes done by the user with the `votes` collection.

**Comment by EugeneTeu** [comment]
How about instead of `Vote` we have `Upvote` and `Downvote`?  two collections

**Comment by EugeneTeu** [comment]
> Route to upvote should be `POST /api/questions/:id/upvote` to upvote, and similarly to downvote and for answers. Upvoting a question/answer should do the following:
> 
> 1. Find if ques/ans exists
> 2. Increment its `upvotes` or `downvotes` field by 1
> 3. Create a new `Vote` document linking the user to the ques/ans
> 
> 

Agreed

**Comment by EugeneTeu** [comment]
```typescript
interface Upvote {
  value: VoteType.UPVOTE;
}

interface Downvote {
  value: VoteType.DOWNVOTE;
}

interface BaseVote extends Util {
  userId: ObjectId;
  type: Upvote | Downvote;
}


```

What about this?

**Comment by AaronCQL** [comment]
Wouldn't this make `BaseVote`'s `type` be an object with a single key `value`?

**Comment by EugeneTeu** [comment]
lol in the end same as using 1 | -1
